/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    accounts: AccountAuthOperations;
  };
  blocks: {};
  collections: {
    accounts: Account;
    users: User;
    categories: Category;
    merchants: Merchant;
    'merchant-skus': MerchantSkus;
    devices: Device;
    'return-info': ReturnInfo;
    'shipping-templates': ShippingTemplate;
    'user-merchant-credit': UserMerchantCredit;
    orders: Order;
    logistics: Logistic;
    payments: Payment;
    statements: Statement;
    'audit-logs': AuditLog;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    accounts: {
      users: 'users';
    };
  };
  collectionsSelect: {
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    merchants: MerchantsSelect<false> | MerchantsSelect<true>;
    'merchant-skus': MerchantSkusSelect<false> | MerchantSkusSelect<true>;
    devices: DevicesSelect<false> | DevicesSelect<true>;
    'return-info': ReturnInfoSelect<false> | ReturnInfoSelect<true>;
    'shipping-templates': ShippingTemplatesSelect<false> | ShippingTemplatesSelect<true>;
    'user-merchant-credit': UserMerchantCreditSelect<false> | UserMerchantCreditSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    logistics: LogisticsSelect<false> | LogisticsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    statements: StatementsSelect<false> | StatementsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: Account & {
    collection: 'accounts';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AccountAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  /**
   * 用于登录和接收验证码（与邮箱二选一）
   */
  phone?: string | null;
  users?: {
    docs?: (number | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * 禁用后无法登录
   */
  status: 'active' | 'disabled';
  last_login_at?: string | null;
  /**
   * 内部备注
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  /**
   * 用于登录和接收通知（与手机号二选一）
   */
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 关联的登录账号（一个账号可以有多个业务身份）
   */
  account: number | Account;
  /**
   * 决定用户的基本业务类型
   */
  user_type: 'customer' | 'merchant' | 'platform';
  /**
   * 决定用户在系统中的权限，只能由管理员设置
   */
  role: 'customer' | 'merchant_member' | 'merchant_admin' | 'platform_operator' | 'platform_admin' | 'platform_support';
  /**
   * 商户类型必填
   */
  merchant?: (number | null) | Merchant;
  /**
   * 禁用后该业务身份无法使用
   */
  status: 'active' | 'disabled';
  /**
   * 该业务身份最后被使用的时间
   */
  last_login_at?: string | null;
  /**
   * 内部备注
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchants".
 */
export interface Merchant {
  id: number;
  name: string;
  contact: {
    name: string;
    phone: string;
    email?: string | null;
  };
  /**
   * 用于对账和打款
   */
  settlement_account?: {
    account_name?: string | null;
    account_number?: string | null;
    bank_name?: string | null;
  };
  /**
   * 上传营业执照扫描件
   */
  business_license?: (number | null) | Media;
  /**
   * 商户的办公地址
   */
  address?: string | null;
  status: 'pending' | 'approved' | 'rejected' | 'disabled';
  /**
   * 平台生成的唯一邀请码
   */
  invitation_code?: string | null;
  /**
   * 平台运营人员
   */
  invited_by?: (number | null) | User;
  invited_at?: string | null;
  approved_at?: string | null;
  approved_by?: (number | null) | User;
  rejection_reason?: string | null;
  /**
   * 内部备注，商户不可见
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * 留空表示顶级类目
   */
  parent?: (number | null) | Category;
  /**
   * 自动生成，如：/电子设备/无人机
   */
  path?: string | null;
  /**
   * 数字越小越靠前
   */
  sort?: number | null;
  status?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchant-skus".
 */
export interface MerchantSkus {
  id: number;
  /**
   * 该SKU归属的商户
   */
  merchant: number | Merchant;
  category: number | Category;
  /**
   * 如：大疆 Mavic 3 Pro
   */
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 单位：元/天
   */
  daily_fee: number;
  /**
   * 用于授信计算和押金参考
   */
  device_value: number;
  /**
   * 可租数量，MVP不做租期日历
   */
  inventory_qty: number;
  /**
   * 留空则使用商户默认模板
   */
  shipping_template?: (number | null) | ShippingTemplate;
  /**
   * 上架后对授信用户可见
   */
  is_listed?: boolean | null;
  /**
   * MVP默认需平台审核后才能上架
   */
  listing_status?: ('draft' | 'pending' | 'approved' | 'rejected') | null;
  rejection_reason?: string | null;
  specifications?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-templates".
 */
export interface ShippingTemplate {
  id: number;
  merchant: number | Merchant;
  /**
   * 如：默认运费模板、偏远地区模板
   */
  name: string;
  /**
   * 每次修改自动递增，用于订单快照追溯
   */
  version?: number | null;
  /**
   * 未匹配到指定地区时的运费
   */
  default_fee: number;
  /**
   * 按地区设置固定价，优先级：不发地区 > 指定地区价 > 默认价
   */
  region_rules?:
    | {
        /**
         * 如：110000（北京）、440300（深圳）
         */
        region_code_path: string;
        /**
         * 如：北京市、广东省深圳市
         */
        region_name: string;
        fee: number;
        id?: string | null;
      }[]
    | null;
  /**
   * 命中后下单拦截，平台可豁免
   */
  blacklist_regions?:
    | {
        region_code_path: string;
        region_name: string;
        /**
         * 如：偏远地区、无物流覆盖
         */
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'inactive' | 'archived';
  /**
   * SKU未指定模板时使用此模板
   */
  is_default?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices".
 */
export interface Device {
  id: number;
  /**
   * 该设备属于哪个商户SKU
   */
  merchant_sku: number | MerchantSkus;
  /**
   * 唯一标识，用于追踪和绑定订单
   */
  sn: string;
  status: 'in_stock' | 'in_rent' | 'in_transit' | 'in_maintenance' | 'scrapped';
  /**
   * 如果设备正在租赁中，关联到当前订单
   */
  current_order?: (number | null) | Order;
  purchase_date?: string | null;
  purchase_price?: number | null;
  condition?: ('new' | 'like_new' | 'excellent' | 'good' | 'fair') | null;
  /**
   * 设备特殊说明、维修记录等
   */
  notes?: string | null;
  /**
   * 可生成设备专属二维码，用于扫码管理
   */
  qr_code?: (number | null) | Media;
  last_maintenance_date?: string | null;
  /**
   * 该设备累计被租赁的次数
   */
  rental_count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * 自动生成的唯一订单号
   */
  order_no: string;
  /**
   * 第三方支付平台返回的支付单号（冗余字段，方便快速查询）
   */
  out_pay_no?: string | null;
  customer: number | User;
  /**
   * 自动从 SKU 中获取
   */
  merchant?: (number | null) | Merchant;
  merchant_sku: number | MerchantSkus;
  /**
   * 发货时绑定的设备ID（系统会根据设备SN自动查找或创建设备）
   */
  device?: (number | null) | Device;
  /**
   * 发货时输入设备SN，系统会自动处理设备绑定
   */
  device_sn?: string | null;
  /**
   * 对应PRD状态机流转
   */
  status: 'NEW' | 'PAID' | 'TO_SHIP' | 'SHIPPED' | 'IN_RENT' | 'RETURNING' | 'RETURNED' | 'COMPLETED' | 'CANCELED';
  /**
   * 商户实际发货的时间
   */
  shipping_date?: string | null;
  rent_start_date: string;
  rent_end_date: string;
  /**
   * 订单创建的时间
   */
  order_creat_at?: string | null;
  /**
   * 自动计算：rent_end_date - rent_start_date
   */
  rent_days?: number | null;
  /**
   * 发货当日次日00:00（默认UTC+8）
   */
  actual_start_date?: string | null;
  /**
   * 商户确认收到归还设备的时间，用于计算实际租期
   */
  return_confirm_time?: string | null;
  /**
   * 默认北京时间（UTC+8）
   */
  timezone?: string | null;
  /**
   * 下单时SKU的日租金(自动从SKU获取)
   */
  daily_fee_snapshot?: number | null;
  /**
   * 用于授信冻结(自动从SKU获取)
   */
  device_value_snapshot?: number | null;
  /**
   * 下单时计算的运费(自动计算)
   */
  shipping_fee_snapshot?: number | null;
  /**
   * 订单使用的运费模板（自动从 SKU 获取）
   */
  shipping_template_id?: (number | null) | ShippingTemplate;
  /**
   * 商户在发货后添加的运费补差价
   */
  shipping_fee_adjustment?: number | null;
  /**
   * 按设备价值冻结，完成时释放
   */
  credit_hold_amount?: number | null;
  shipping_address: {
    contact_name: string;
    contact_phone: string;
    province: string;
    city: string;
    district: string;
    address: string;
    region_code?: string | null;
  };
  /**
   * 商户可在"归还中"之前修改归还地址
   */
  return_address?: {
    /**
     * 订单状态为 RETURNING 及之后不可修改
     */
    contact_name?: string | null;
    /**
     * 订单状态为 RETURNING 及之后不可修改
     */
    contact_phone?: string | null;
    /**
     * 订单状态为 RETURNING 及之后不可修改
     */
    province?: string | null;
    /**
     * 订单状态为 RETURNING 及之后不可修改
     */
    city?: string | null;
    /**
     * 订单状态为 RETURNING 及之后不可修改
     */
    district?: string | null;
    /**
     * 订单状态为 RETURNING 及之后不可修改
     */
    address?: string | null;
    /**
     * 订单状态为 RETURNING 及之后不可修改
     */
    postal_code?: string | null;
  };
  /**
   * 订单的发货物流信息（logistics_type=shipping）
   */
  shipping_logistics?: (number | null) | Logistic;
  /**
   * 订单的归还物流信息（logistics_type=return）
   */
  return_logistics?: (number | null) | Logistic;
  /**
   * 包含租赁支付、逾期补收、改址差额等所有支付
   */
  payments?: (number | Payment)[] | null;
  statement?: (number | null) | Statement;
  is_overdue?: boolean | null;
  overdue_days?: number | null;
  /**
   * ceil(逾期小时/24) × 日费率
   */
  overdue_amount?: number | null;
  /**
   * 租金 + 运费 + 逾期
   */
  order_total_amount?: number | null;
  /**
   * 发货时的物流单号
   */
  shipping_no?: string | null;
  /**
   * 用户归还设备时的物流单号
   */
  return_no?: string | null;
  notes?: string | null;
  status_history?:
    | {
        status: string;
        changed_at: string;
        operator?: (number | null) | User;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logistics".
 */
export interface Logistic {
  id: number;
  /**
   * 系统生成的物流记录唯一标识
   */
  logistics_id: string;
  /**
   * 关联的订单编号
   */
  order_no: string;
  /**
   * 关联订单对象（用于查询）
   */
  order: number | Order;
  /**
   * 如：顺丰、德邦
   */
  carrier?: string | null;
  /**
   * 承运商提供的物流单号
   */
  logistics_no?: string | null;
  ship_at?: string | null;
  /**
   * 区分是发货还是归还
   */
  logistics_type: 'shipping' | 'return';
  /**
   * 物流API回传或商户确认
   */
  sign_at?: string | null;
  tracking_events?:
    | {
        time: string;
        desc: string;
        location?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  /**
   * 系统生成的唯一交易号
   */
  transaction_no: string;
  /**
   * 关联的订单编号
   */
  order_no: string;
  /**
   * 关联订单对象（用于查询）
   */
  order: number | Order;
  /**
   * 微信/支付宝等第三方支付平台返回的支付单号
   */
  out_pay_no?: string | null;
  /**
   * 区分支付用途（统一管理所有支付场景）
   */
  type: 'rent' | 'rent_canceled' | 'overdue' | 'addr_up' | 'addr_down';
  /**
   * 正数表示应收款，负数表示退款
   */
  amount: number;
  /**
   * 仅在 type=rent 时需要填写
   */
  amount_detail?: {
    /**
     * 租期天数 × 日租金
     */
    rent?: number | null;
    shipping?: number | null;
  };
  status: 'pending' | 'paid' | 'refunded' | 'failed';
  /**
   * 支付订单创建的时间
   */
  pay_creat_at?: string | null;
  paid_at?: string | null;
  channel?: ('wechat' | 'alipay' | 'bank' | 'other') | null;
  /**
   * 支付备注、退款原因等
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statements".
 */
export interface Statement {
  id: number;
  /**
   * 自动生成
   */
  statement_no: string;
  order: number | Order;
  issued_at: string;
  amount_rent: number;
  amount_shipping: number;
  amount_overdue?: number | null;
  /**
   * 改址差额等
   */
  amount_surcharge?: number | null;
  /**
   * 租金+运费+逾期+其他
   */
  amount_total: number;
  /**
   * 包含设备SN、关键时间戳等
   */
  details_json?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('issued' | 'confirmed' | 'disputed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "return-info".
 */
export interface ReturnInfo {
  id: number;
  /**
   * 该归还信息所属的商户
   */
  merchant: number | Merchant;
  /**
   * 设备回收的联系人姓名
   */
  return_contact_name: string;
  /**
   * 设备回收的联系人电话（建议格式：1xxxxxxxxxx）
   */
  return_contact_phone: string;
  return_address: {
    province: string;
    city: string;
    district?: string | null;
    /**
     * 街道、门牌号等详细地址信息
     */
    address: string;
    postal_code?: string | null;
  };
  /**
   * 停用后该地址将不可用于新订单
   */
  status: 'active' | 'disabled';
  /**
   * 每个商户只能有一个默认归还地址
   */
  is_default?: boolean | null;
  /**
   * 地址相关的补充说明，如营业时间、特殊要求等
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-merchant-credit".
 */
export interface UserMerchantCredit {
  id: number;
  /**
   * 被授信的用户
   */
  user: number | User;
  /**
   * 授信的商户
   */
  merchant: number | Merchant;
  /**
   * 用户可以冻结的最大金额（按设备价值计算）
   */
  credit_limit: number;
  /**
   * 当前已冻结的金额，订单完成后释放
   */
  used_credit?: number | null;
  /**
   * 计算字段：credit_limit - used_credit
   */
  available_credit?: number | null;
  /**
   * 禁用后用户无法查看商户SKU和下单
   */
  status: 'active' | 'disabled' | 'frozen';
  /**
   * 授信记录的创建来源
   */
  source: 'manual';
  granted_at?: string | null;
  /**
   * 商户管理员
   */
  granted_by?: (number | null) | User;
  revoked_at?: string | null;
  revoked_by?: (number | null) | User;
  /**
   * 授信原因、调整记录等
   */
  notes?: string | null;
  credit_history?:
    | {
        date: string;
        old_limit: number;
        new_limit: number;
        reason?: string | null;
        operator?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  entity: 'order' | 'credit' | 'merchant' | 'sku' | 'user' | 'shipping_template';
  entity_id: string;
  action:
    | 'create'
    | 'update'
    | 'delete'
    | 'force_transition'
    | 'exempt_blacklist'
    | 'adjust_credit'
    | 'revoke_credit'
    | 'approve'
    | 'reject';
  operator?: (number | null) | User;
  /**
   * 冗余字段，便于查询
   */
  operator_role?: string | null;
  /**
   * 敏感操作必填
   */
  reason?: string | null;
  /**
   * 用于追溯
   */
  before_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip_address?: string | null;
  user_agent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'merchants';
        value: number | Merchant;
      } | null)
    | ({
        relationTo: 'merchant-skus';
        value: number | MerchantSkus;
      } | null)
    | ({
        relationTo: 'devices';
        value: number | Device;
      } | null)
    | ({
        relationTo: 'return-info';
        value: number | ReturnInfo;
      } | null)
    | ({
        relationTo: 'shipping-templates';
        value: number | ShippingTemplate;
      } | null)
    | ({
        relationTo: 'user-merchant-credit';
        value: number | UserMerchantCredit;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'logistics';
        value: number | Logistic;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'statements';
        value: number | Statement;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'accounts';
    value: number | Account;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'accounts';
    value: number | Account;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  phone?: T;
  users?: T;
  status?: T;
  last_login_at?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  account?: T;
  user_type?: T;
  role?: T;
  merchant?: T;
  status?: T;
  last_login_at?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  path?: T;
  sort?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchants_select".
 */
export interface MerchantsSelect<T extends boolean = true> {
  name?: T;
  contact?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  settlement_account?:
    | T
    | {
        account_name?: T;
        account_number?: T;
        bank_name?: T;
      };
  business_license?: T;
  address?: T;
  status?: T;
  invitation_code?: T;
  invited_by?: T;
  invited_at?: T;
  approved_at?: T;
  approved_by?: T;
  rejection_reason?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchant-skus_select".
 */
export interface MerchantSkusSelect<T extends boolean = true> {
  merchant?: T;
  category?: T;
  name?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  daily_fee?: T;
  device_value?: T;
  inventory_qty?: T;
  shipping_template?: T;
  is_listed?: T;
  listing_status?: T;
  rejection_reason?: T;
  specifications?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  created_by?: T;
  updated_by?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices_select".
 */
export interface DevicesSelect<T extends boolean = true> {
  merchant_sku?: T;
  sn?: T;
  status?: T;
  current_order?: T;
  purchase_date?: T;
  purchase_price?: T;
  condition?: T;
  notes?: T;
  qr_code?: T;
  last_maintenance_date?: T;
  rental_count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "return-info_select".
 */
export interface ReturnInfoSelect<T extends boolean = true> {
  merchant?: T;
  return_contact_name?: T;
  return_contact_phone?: T;
  return_address?:
    | T
    | {
        province?: T;
        city?: T;
        district?: T;
        address?: T;
        postal_code?: T;
      };
  status?: T;
  is_default?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-templates_select".
 */
export interface ShippingTemplatesSelect<T extends boolean = true> {
  merchant?: T;
  name?: T;
  version?: T;
  default_fee?: T;
  region_rules?:
    | T
    | {
        region_code_path?: T;
        region_name?: T;
        fee?: T;
        id?: T;
      };
  blacklist_regions?:
    | T
    | {
        region_code_path?: T;
        region_name?: T;
        reason?: T;
        id?: T;
      };
  status?: T;
  is_default?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-merchant-credit_select".
 */
export interface UserMerchantCreditSelect<T extends boolean = true> {
  user?: T;
  merchant?: T;
  credit_limit?: T;
  used_credit?: T;
  available_credit?: T;
  status?: T;
  source?: T;
  granted_at?: T;
  granted_by?: T;
  revoked_at?: T;
  revoked_by?: T;
  notes?: T;
  credit_history?:
    | T
    | {
        date?: T;
        old_limit?: T;
        new_limit?: T;
        reason?: T;
        operator?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  order_no?: T;
  out_pay_no?: T;
  customer?: T;
  merchant?: T;
  merchant_sku?: T;
  device?: T;
  device_sn?: T;
  status?: T;
  shipping_date?: T;
  rent_start_date?: T;
  rent_end_date?: T;
  order_creat_at?: T;
  rent_days?: T;
  actual_start_date?: T;
  return_confirm_time?: T;
  timezone?: T;
  daily_fee_snapshot?: T;
  device_value_snapshot?: T;
  shipping_fee_snapshot?: T;
  shipping_template_id?: T;
  shipping_fee_adjustment?: T;
  credit_hold_amount?: T;
  shipping_address?:
    | T
    | {
        contact_name?: T;
        contact_phone?: T;
        province?: T;
        city?: T;
        district?: T;
        address?: T;
        region_code?: T;
      };
  return_address?:
    | T
    | {
        contact_name?: T;
        contact_phone?: T;
        province?: T;
        city?: T;
        district?: T;
        address?: T;
        postal_code?: T;
      };
  shipping_logistics?: T;
  return_logistics?: T;
  payments?: T;
  statement?: T;
  is_overdue?: T;
  overdue_days?: T;
  overdue_amount?: T;
  order_total_amount?: T;
  shipping_no?: T;
  return_no?: T;
  notes?: T;
  status_history?:
    | T
    | {
        status?: T;
        changed_at?: T;
        operator?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logistics_select".
 */
export interface LogisticsSelect<T extends boolean = true> {
  logistics_id?: T;
  order_no?: T;
  order?: T;
  carrier?: T;
  logistics_no?: T;
  ship_at?: T;
  logistics_type?: T;
  sign_at?: T;
  tracking_events?:
    | T
    | {
        time?: T;
        desc?: T;
        location?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  transaction_no?: T;
  order_no?: T;
  order?: T;
  out_pay_no?: T;
  type?: T;
  amount?: T;
  amount_detail?:
    | T
    | {
        rent?: T;
        shipping?: T;
      };
  status?: T;
  pay_creat_at?: T;
  paid_at?: T;
  channel?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statements_select".
 */
export interface StatementsSelect<T extends boolean = true> {
  statement_no?: T;
  order?: T;
  issued_at?: T;
  amount_rent?: T;
  amount_shipping?: T;
  amount_overdue?: T;
  amount_surcharge?: T;
  amount_total?: T;
  details_json?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  entity?: T;
  entity_id?: T;
  action?: T;
  operator?: T;
  operator_role?: T;
  reason?: T;
  before_data?: T;
  after_data?: T;
  ip_address?: T;
  user_agent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}